### ISSUE TITLE
Not checking for repeating next_cursor

### ISSUE THREAD

**Issue by tomc603** [quintindunn/vsco.py#1]
The `_load_more()` function of the `VscoProfile` class doesn't check the value of `next_cursor` to see if it's equal to the current value of `cursor`. The site appears to be returning the current cursor as the value of `next_cursor` when there is no more pagination to explore.

https://github.com/quintindunn/vsco.py/blob/91c7173983548659405526284d0f30dbe5a337bb/vsco/vsco.py#L202

Adding a simple equivalence check fixes this.

Looking at the bigger picture, It might be a good idea to invert this function entirely, though, to do a depth-first fetch of `media`. This would prevent the need to pass `media` to the recursive calls to `_load_more()`, and would collapse the `if/else` on line 204. But that's totally not necessary.

**Comment by quintindunn** [comment]
Hey, when I  created this library it would return nothing as the next_cursor value though based off what you said I'm assuming that has changed. I'm currently in class so I cannot actually test to see if I can replicate the issue, but I'm going to check it later tonight. For now I'll just make a separate branch for it.

**Comment by quintindunn** [comment]
After testing on the VSCO website I saw it not returning a value for next_cursor when it ended pagination, so the code still worked for me, with that the performance impact of adding the check is so negligible that I added it.

Regarding reworking the function, I might change that in the future though I'm not sure. As for now I'm going to keep it the same as it was, but I'll keep this in mind.
